repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        name: ' files/ yaml 路 Check YAML syntax'
      - id: check-json
        name: ' files/ json 路 Check JSON syntax'
      - id: check-toml
        name: ' files/ toml 路 Check TOML syntax'
      - id: check-xml
        name: ' files/ xml 路 Check XML syntax'
      - id: check-added-large-files
        name: ' files/ size 路 Check for large files'
      - id: end-of-file-fixer
        name: ' files/ format 路 Fix end of file'
        exclude: '.*\.gql$'
      - id: trailing-whitespace
        name: ' files/ format 路 Remove trailing whitespace'
      - id: check-case-conflict
        name: ' filesystem/ names 路 Check case sensitivity'
      - id: check-symlinks
        name: ' filesystem/ symlink 路 Check symlink validity'
      - id: check-executables-have-shebangs
        name: ' filesystem/锔 exec 路 Verify shebang presence'
      - id: check-shebang-scripts-are-executable
        name: ' filesystem/锔 exec 路 Verify script permissions'
      - id: destroyed-symlinks
        name: ' filesystem/ symlink 路 Detect broken symlinks'
      - id: detect-private-key
        name: ' security/ key 路 Detect private keys'
      - id: check-merge-conflict
        name: ' git/锔 merge 路 Check for merge conflicts'
      - id: forbid-submodules
        name: ' git/ submodule 路 Forbid submodules'
      - id: no-commit-to-branch
        name: ' git/ branch 路 Prevent commits to main'
        args: [--branch, main]
  - repo: https://github.com/pre-commit/pre-commit
    rev: v4.2.0
    hooks:
      - id: validate_manifest
        name: ' hooks 路 Validate pre-commit manifest'
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
      - id: commitizen
        name: ' git 路 Validate commit message'
        stages: [commit-msg]
        additional_dependencies: [cz-conventional-gitmoji]
      - id: commitizen-branch
        name: ' git 路 Validate commit message branch'
        stages: [pre-push]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.22.0
    hooks:
      - id: commitlint
        name: ' git 路 Lint commit messages'
        stages: [commit-msg]
  - repo: https://github.com/google/yamlfmt
    rev: v0.17.2
    hooks:
      - id: yamlfmt
        name: ' files/ yaml 路 Format YAML files'
        exclude: |
          (?x)^(
              node_modules/ |
              pnpm-lock.yaml |
          )$
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.27.2
    hooks:
      - id: gitleaks
        name: ' security/ secrets 路 Detect leaked credentials'
        exclude: |
          (?x)^(
              node_modules/ |
              pnpm-lock.yaml |
              nx.json
          )$
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        name: ' security/ secrets 路 Find unintentional secrets'
        args: ['--exclude-files', '.env']
        exclude: |
          (?x)^(
              node_modules/ |
              pnpm-lock.yaml |
              nx.json
          )$
  # - repo: https://github.com/biomejs/pre-commit
  #   rev: 'v2.0.6'
  #   hooks:
  #     - id: biome-check
  #       name: ' javascript 路 Lint, format, and safe fixes with Biome'
  #       additional_dependencies: ['@biomejs/biome@2.0.6']
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.3.0
    hooks:
      - id: sqlfluff-fix
        name: ' SQL 路 Attempts to fix rule violations.'
      # STRICT
      - id: sqlfluff-lint
        name: ' SQL 路 Lint SQL code files'
  - repo: local
    hooks:
      - id: lint-staged
        name: lint-staged
        entry: pnpm lint-staged
        language: system
        stages: [pre-commit]
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
